version: '3'

services:

  issuer:
    platform: linux/x86_64
    restart: always
    container_name: issuer
    image: issuer
    build:
      context: .
    ports:
      - "5050:5050"
    volumes:
      - ./code/src:/root/issuer/src
    networks:
      - issuer_network

networks:
  issuer_network:

